### PR TITLE
fix front-end stuffs

### PR DESCRIPTION
**Pull request by IanWen103026**
add main-container to index.html.erb
move part of menu's javascript to an external file
rename "money" to "balance"
format html

### CODE REVIEW

**Review by AaronWu-train — COMMENTED** [review]
Require code formatting by Prettier
ask @ckeisc43rd-cjtsai for installation

**Comment by AaronWu-train** [comment]
Codes seems ok

**Review by AaronWu-train — DISMISSED** [review]

**Comment by AaronWu-train** [comment]
@IanWen103026 I've cherry picked some old changes from 56d82d963abff776cbe84206cda58fc93dd41a28, so the pictures should be restored.
Please check whether the code is correct or not.

**Comment by IanWen103026** [comment]
The HTML file, JavaScript file, and custom.css appear to be structurally sound and functioning correctly upon inspection.

**Review by AaronWu-train — APPROVED** [review]

**Pull request merged**
